## PostgreSQL - Production Profile ##
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/pokemon_tcg}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:}

## JPA ##
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

## PokemonTCG API ##
pokemontcg.api.base-url=https://api.pokemontcg.io/v2
pokemontcg.api.key=${POKEMONTCG_API_KEY:}
